/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEntierVarsimple extends PVarsimple
{
    private PVarent _varent_;

    public AEntierVarsimple()
    {
        // Constructor
    }

    public AEntierVarsimple(
        @SuppressWarnings("hiding") PVarent _varent_)
    {
        // Constructor
        setVarent(_varent_);

    }

    @Override
    public Object clone()
    {
        return new AEntierVarsimple(
            cloneNode(this._varent_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEntierVarsimple(this);
    }

    public PVarent getVarent()
    {
        return this._varent_;
    }

    public void setVarent(PVarent node)
    {
        if(this._varent_ != null)
        {
            this._varent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varent_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varent_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varent_ == child)
        {
            this._varent_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varent_ == oldChild)
        {
            setVarent((PVarent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
