/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFonctionExpr7 extends PExpr7
{
    private PDeffonction _deffonction_;

    public AFonctionExpr7()
    {
        // Constructor
    }

    public AFonctionExpr7(
        @SuppressWarnings("hiding") PDeffonction _deffonction_)
    {
        // Constructor
        setDeffonction(_deffonction_);

    }

    @Override
    public Object clone()
    {
        return new AFonctionExpr7(
            cloneNode(this._deffonction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFonctionExpr7(this);
    }

    public PDeffonction getDeffonction()
    {
        return this._deffonction_;
    }

    public void setDeffonction(PDeffonction node)
    {
        if(this._deffonction_ != null)
        {
            this._deffonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._deffonction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._deffonction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._deffonction_ == child)
        {
            this._deffonction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._deffonction_ == oldChild)
        {
            setDeffonction((PDeffonction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
