/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMoinsExpr4 extends PExpr4
{
    private PExpr4 _expr4_;
    private TMoins _moins_;
    private PExpr5 _expr5_;

    public AMoinsExpr4()
    {
        // Constructor
    }

    public AMoinsExpr4(
        @SuppressWarnings("hiding") PExpr4 _expr4_,
        @SuppressWarnings("hiding") TMoins _moins_,
        @SuppressWarnings("hiding") PExpr5 _expr5_)
    {
        // Constructor
        setExpr4(_expr4_);

        setMoins(_moins_);

        setExpr5(_expr5_);

    }

    @Override
    public Object clone()
    {
        return new AMoinsExpr4(
            cloneNode(this._expr4_),
            cloneNode(this._moins_),
            cloneNode(this._expr5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoinsExpr4(this);
    }

    public PExpr4 getExpr4()
    {
        return this._expr4_;
    }

    public void setExpr4(PExpr4 node)
    {
        if(this._expr4_ != null)
        {
            this._expr4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr4_ = node;
    }

    public TMoins getMoins()
    {
        return this._moins_;
    }

    public void setMoins(TMoins node)
    {
        if(this._moins_ != null)
        {
            this._moins_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moins_ = node;
    }

    public PExpr5 getExpr5()
    {
        return this._expr5_;
    }

    public void setExpr5(PExpr5 node)
    {
        if(this._expr5_ != null)
        {
            this._expr5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr4_)
            + toString(this._moins_)
            + toString(this._expr5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr4_ == child)
        {
            this._expr4_ = null;
            return;
        }

        if(this._moins_ == child)
        {
            this._moins_ = null;
            return;
        }

        if(this._expr5_ == child)
        {
            this._expr5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr4_ == oldChild)
        {
            setExpr4((PExpr4) newChild);
            return;
        }

        if(this._moins_ == oldChild)
        {
            setMoins((TMoins) newChild);
            return;
        }

        if(this._expr5_ == oldChild)
        {
            setExpr5((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
