/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleFctdecvar extends PFctdecvar
{
    private PVarsimple _varsimple_;
    private PVarmultiple _varmultiple_;

    public AMultipleFctdecvar()
    {
        // Constructor
    }

    public AMultipleFctdecvar(
        @SuppressWarnings("hiding") PVarsimple _varsimple_,
        @SuppressWarnings("hiding") PVarmultiple _varmultiple_)
    {
        // Constructor
        setVarsimple(_varsimple_);

        setVarmultiple(_varmultiple_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleFctdecvar(
            cloneNode(this._varsimple_),
            cloneNode(this._varmultiple_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleFctdecvar(this);
    }

    public PVarsimple getVarsimple()
    {
        return this._varsimple_;
    }

    public void setVarsimple(PVarsimple node)
    {
        if(this._varsimple_ != null)
        {
            this._varsimple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varsimple_ = node;
    }

    public PVarmultiple getVarmultiple()
    {
        return this._varmultiple_;
    }

    public void setVarmultiple(PVarmultiple node)
    {
        if(this._varmultiple_ != null)
        {
            this._varmultiple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varmultiple_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varsimple_)
            + toString(this._varmultiple_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varsimple_ == child)
        {
            this._varsimple_ = null;
            return;
        }

        if(this._varmultiple_ == child)
        {
            this._varmultiple_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varsimple_ == oldChild)
        {
            setVarsimple((PVarsimple) newChild);
            return;
        }

        if(this._varmultiple_ == oldChild)
        {
            setVarmultiple((PVarmultiple) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
