/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultiExpr5 extends PExpr5
{
    private PExpr5 _expr5_;
    private TMulti _multi_;
    private PExpr6 _expr6_;

    public AMultiExpr5()
    {
        // Constructor
    }

    public AMultiExpr5(
        @SuppressWarnings("hiding") PExpr5 _expr5_,
        @SuppressWarnings("hiding") TMulti _multi_,
        @SuppressWarnings("hiding") PExpr6 _expr6_)
    {
        // Constructor
        setExpr5(_expr5_);

        setMulti(_multi_);

        setExpr6(_expr6_);

    }

    @Override
    public Object clone()
    {
        return new AMultiExpr5(
            cloneNode(this._expr5_),
            cloneNode(this._multi_),
            cloneNode(this._expr6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiExpr5(this);
    }

    public PExpr5 getExpr5()
    {
        return this._expr5_;
    }

    public void setExpr5(PExpr5 node)
    {
        if(this._expr5_ != null)
        {
            this._expr5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr5_ = node;
    }

    public TMulti getMulti()
    {
        return this._multi_;
    }

    public void setMulti(TMulti node)
    {
        if(this._multi_ != null)
        {
            this._multi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multi_ = node;
    }

    public PExpr6 getExpr6()
    {
        return this._expr6_;
    }

    public void setExpr6(PExpr6 node)
    {
        if(this._expr6_ != null)
        {
            this._expr6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr5_)
            + toString(this._multi_)
            + toString(this._expr6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr5_ == child)
        {
            this._expr5_ = null;
            return;
        }

        if(this._multi_ == child)
        {
            this._multi_ = null;
            return;
        }

        if(this._expr6_ == child)
        {
            this._expr6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr5_ == oldChild)
        {
            setExpr5((PExpr5) newChild);
            return;
        }

        if(this._multi_ == oldChild)
        {
            setMulti((TMulti) newChild);
            return;
        }

        if(this._expr6_ == oldChild)
        {
            setExpr6((PExpr6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
