/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANomvarExpr7 extends PExpr7
{
    private TNom _nom_;

    public ANomvarExpr7()
    {
        // Constructor
    }

    public ANomvarExpr7(
        @SuppressWarnings("hiding") TNom _nom_)
    {
        // Constructor
        setNom(_nom_);

    }

    @Override
    public Object clone()
    {
        return new ANomvarExpr7(
            cloneNode(this._nom_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANomvarExpr7(this);
    }

    public TNom getNom()
    {
        return this._nom_;
    }

    public void setNom(TNom node)
    {
        if(this._nom_ != null)
        {
            this._nom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nom_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nom_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nom_ == child)
        {
            this._nom_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nom_ == oldChild)
        {
            setNom((TNom) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
