/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASansargDeffonction extends PDeffonction
{
    private TNom _nom_;
    private TParentheseo _parentheseo_;
    private TParenthesef _parenthesef_;
    private PDecvar2 _decvar2_;
    private PBloc _bloc_;

    public ASansargDeffonction()
    {
        // Constructor
    }

    public ASansargDeffonction(
        @SuppressWarnings("hiding") TNom _nom_,
        @SuppressWarnings("hiding") TParentheseo _parentheseo_,
        @SuppressWarnings("hiding") TParenthesef _parenthesef_,
        @SuppressWarnings("hiding") PDecvar2 _decvar2_,
        @SuppressWarnings("hiding") PBloc _bloc_)
    {
        // Constructor
        setNom(_nom_);

        setParentheseo(_parentheseo_);

        setParenthesef(_parenthesef_);

        setDecvar2(_decvar2_);

        setBloc(_bloc_);

    }

    @Override
    public Object clone()
    {
        return new ASansargDeffonction(
            cloneNode(this._nom_),
            cloneNode(this._parentheseo_),
            cloneNode(this._parenthesef_),
            cloneNode(this._decvar2_),
            cloneNode(this._bloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASansargDeffonction(this);
    }

    public TNom getNom()
    {
        return this._nom_;
    }

    public void setNom(TNom node)
    {
        if(this._nom_ != null)
        {
            this._nom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nom_ = node;
    }

    public TParentheseo getParentheseo()
    {
        return this._parentheseo_;
    }

    public void setParentheseo(TParentheseo node)
    {
        if(this._parentheseo_ != null)
        {
            this._parentheseo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseo_ = node;
    }

    public TParenthesef getParenthesef()
    {
        return this._parenthesef_;
    }

    public void setParenthesef(TParenthesef node)
    {
        if(this._parenthesef_ != null)
        {
            this._parenthesef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenthesef_ = node;
    }

    public PDecvar2 getDecvar2()
    {
        return this._decvar2_;
    }

    public void setDecvar2(PDecvar2 node)
    {
        if(this._decvar2_ != null)
        {
            this._decvar2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decvar2_ = node;
    }

    public PBloc getBloc()
    {
        return this._bloc_;
    }

    public void setBloc(PBloc node)
    {
        if(this._bloc_ != null)
        {
            this._bloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nom_)
            + toString(this._parentheseo_)
            + toString(this._parenthesef_)
            + toString(this._decvar2_)
            + toString(this._bloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nom_ == child)
        {
            this._nom_ = null;
            return;
        }

        if(this._parentheseo_ == child)
        {
            this._parentheseo_ = null;
            return;
        }

        if(this._parenthesef_ == child)
        {
            this._parenthesef_ = null;
            return;
        }

        if(this._decvar2_ == child)
        {
            this._decvar2_ = null;
            return;
        }

        if(this._bloc_ == child)
        {
            this._bloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nom_ == oldChild)
        {
            setNom((TNom) newChild);
            return;
        }

        if(this._parentheseo_ == oldChild)
        {
            setParentheseo((TParentheseo) newChild);
            return;
        }

        if(this._parenthesef_ == oldChild)
        {
            setParenthesef((TParenthesef) newChild);
            return;
        }

        if(this._decvar2_ == oldChild)
        {
            setDecvar2((PDecvar2) newChild);
            return;
        }

        if(this._bloc_ == oldChild)
        {
            setBloc((PBloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
