/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASiInstr extends PInstr
{
    private PInstrsi _instrsi_;

    public ASiInstr()
    {
        // Constructor
    }

    public ASiInstr(
        @SuppressWarnings("hiding") PInstrsi _instrsi_)
    {
        // Constructor
        setInstrsi(_instrsi_);

    }

    @Override
    public Object clone()
    {
        return new ASiInstr(
            cloneNode(this._instrsi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASiInstr(this);
    }

    public PInstrsi getInstrsi()
    {
        return this._instrsi_;
    }

    public void setInstrsi(PInstrsi node)
    {
        if(this._instrsi_ != null)
        {
            this._instrsi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrsi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrsi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrsi_ == child)
        {
            this._instrsi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrsi_ == oldChild)
        {
            setInstrsi((PInstrsi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
