/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASisinonInstrsi extends PInstrsi
{
    private TSi _si_;
    private PExpr _expr_;
    private TAlors _alors_;
    private PBloc _bloc_;
    private PInstrsinon _instrsinon_;

    public ASisinonInstrsi()
    {
        // Constructor
    }

    public ASisinonInstrsi(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PBloc _bloc_,
        @SuppressWarnings("hiding") PInstrsinon _instrsinon_)
    {
        // Constructor
        setSi(_si_);

        setExpr(_expr_);

        setAlors(_alors_);

        setBloc(_bloc_);

        setInstrsinon(_instrsinon_);

    }

    @Override
    public Object clone()
    {
        return new ASisinonInstrsi(
            cloneNode(this._si_),
            cloneNode(this._expr_),
            cloneNode(this._alors_),
            cloneNode(this._bloc_),
            cloneNode(this._instrsinon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASisinonInstrsi(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PBloc getBloc()
    {
        return this._bloc_;
    }

    public void setBloc(PBloc node)
    {
        if(this._bloc_ != null)
        {
            this._bloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloc_ = node;
    }

    public PInstrsinon getInstrsinon()
    {
        return this._instrsinon_;
    }

    public void setInstrsinon(PInstrsinon node)
    {
        if(this._instrsinon_ != null)
        {
            this._instrsinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrsinon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._expr_)
            + toString(this._alors_)
            + toString(this._bloc_)
            + toString(this._instrsinon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._bloc_ == child)
        {
            this._bloc_ = null;
            return;
        }

        if(this._instrsinon_ == child)
        {
            this._instrsinon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._bloc_ == oldChild)
        {
            setBloc((PBloc) newChild);
            return;
        }

        if(this._instrsinon_ == oldChild)
        {
            setInstrsinon((PInstrsinon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
