/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TFonction extends Token
{
    public TFonction()
    {
        super.setText("fonction");
    }

    public TFonction(int line, int pos)
    {
        super.setText("fonction");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFonction(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFonction(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFonction text.");
    }
}
