<Start>
 <AProgramme>
  <ARienDecvar2>
  </ARienDecvar2>
  <AFoncDeffonction2>
   <AArgsDeffonction>
    <AMultipleFctdecvar>
     <AEntierVarsimple>
      <AVarent>
      </AVarent>
     </AEntierVarsimple>
     <ARienVarmultiple>
     </ARienVarmultiple>
    </AMultipleFctdecvar>
    <ARienDecvar2>
    </ARienDecvar2>
    <ABloc>
     <AListListinstr>
      <ARetourInstr>
       <AInstrretour>
        <AExpr2Expr>
         <AExpr3Expr2>
          <AExpr4Expr3>
           <AExpr5Expr4>
            <AExpr6Expr5>
             <APart7Expr6>
              <ANombreExpr7>
              </ANombreExpr7>
             </APart7Expr6>
            </AExpr6Expr5>
           </AExpr5Expr4>
          </AExpr4Expr3>
         </AExpr3Expr2>
        </AExpr2Expr>
       </AInstrretour>
      </ARetourInstr>
      <ARienListinstr>
      </ARienListinstr>
     </AListListinstr>
    </ABloc>
   </AArgsDeffonction>
   <AFoncDeffonction2>
    <ASansargDeffonction>
     <ARienDecvar2>
     </ARienDecvar2>
     <ABloc>
      <AListListinstr>
       <AAppelInstr>
        <ASansargFonctionappel>
        </ASansargFonctionappel>
       </AAppelInstr>
       <ARienListinstr>
       </ARienListinstr>
      </AListListinstr>
     </ABloc>
    </ASansargDeffonction>
    <ARienDeffonction2>
    </ARienDeffonction2>
   </AFoncDeffonction2>
  </AFoncDeffonction2>
 </AProgramme>
</Start>
