<Start>
 <AProgramme>
  <AVarDecvar2>
   <ADecvar>
    <AEntierVarsimple>
     <AVarent>
     </AVarent>
    </AEntierVarsimple>
    <ARienVarmultiple>
    </ARienVarmultiple>
   </ADecvar>
  </AVarDecvar2>
  <AFoncDeffonction2>
   <ASansargDeffonction>
    <ARienDecvar2>
    </ARienDecvar2>
    <ABloc>
     <AListListinstr>
      <ATantqueInstr>
       <AInstrtantque>
        <AExpr2Expr>
         <AExpr3Expr2>
          <AExpr4Expr3>
           <AExpr5Expr4>
            <AExpr6Expr5>
             <APart7Expr6>
              <AExprentreparenthesesExpr7>
               <AExpr2Expr>
                <AEtExpr2>
                 <AExpr3Expr2>
                  <AInfExpr3>
                   <AExpr4Expr3>
                    <AExpr5Expr4>
                     <AExpr6Expr5>
                      <APart7Expr6>
                       <AVarExpr7>
                        <ASimpleVariable>
                        </ASimpleVariable>
                       </AVarExpr7>
                      </APart7Expr6>
                     </AExpr6Expr5>
                    </AExpr5Expr4>
                   </AExpr4Expr3>
                   <AExpr5Expr4>
                    <AExpr6Expr5>
                     <APart7Expr6>
                      <ANombreExpr7>
                      </ANombreExpr7>
                     </APart7Expr6>
                    </AExpr6Expr5>
                   </AExpr5Expr4>
                  </AInfExpr3>
                 </AExpr3Expr2>
                 <AExpr4Expr3>
                  <AExpr5Expr4>
                   <AExpr6Expr5>
                    <ANonExpr6>
                     <AExprentreparenthesesExpr7>
                      <AExpr2Expr>
                       <AExpr3Expr2>
                        <AInfExpr3>
                         <AExpr4Expr3>
                          <AExpr5Expr4>
                           <AExpr6Expr5>
                            <APart7Expr6>
                             <AVarExpr7>
                              <ASimpleVariable>
                              </ASimpleVariable>
                             </AVarExpr7>
                            </APart7Expr6>
                           </AExpr6Expr5>
                          </AExpr5Expr4>
                         </AExpr4Expr3>
                         <AExpr5Expr4>
                          <AExpr6Expr5>
                           <APart7Expr6>
                            <ANombreExpr7>
                            </ANombreExpr7>
                           </APart7Expr6>
                          </AExpr6Expr5>
                         </AExpr5Expr4>
                        </AInfExpr3>
                       </AExpr3Expr2>
                      </AExpr2Expr>
                     </AExprentreparenthesesExpr7>
                    </ANonExpr6>
                   </AExpr6Expr5>
                  </AExpr5Expr4>
                 </AExpr4Expr3>
                </AEtExpr2>
               </AExpr2Expr>
              </AExprentreparenthesesExpr7>
             </APart7Expr6>
            </AExpr6Expr5>
           </AExpr5Expr4>
          </AExpr4Expr3>
         </AExpr3Expr2>
        </AExpr2Expr>
        <ABloc>
         <AListListinstr>
          <AAffectationInstr>
           <AAffect>
            <ASimpleVariable>
            </ASimpleVariable>
            <AExpr2Expr>
             <AExpr3Expr2>
              <AExpr4Expr3>
               <AExpr5Expr4>
                <AExpr6Expr5>
                 <APart7Expr6>
                  <ALireExpr7>
                   <AFonctionlire>
                   </AFonctionlire>
                  </ALireExpr7>
                 </APart7Expr6>
                </AExpr6Expr5>
               </AExpr5Expr4>
              </AExpr4Expr3>
             </AExpr3Expr2>
            </AExpr2Expr>
           </AAffect>
          </AAffectationInstr>
          <ARienListinstr>
          </ARienListinstr>
         </AListListinstr>
        </ABloc>
       </AInstrtantque>
      </ATantqueInstr>
      <ARienListinstr>
      </ARienListinstr>
     </AListListinstr>
    </ABloc>
   </ASansargDeffonction>
   <ARienDeffonction2>
   </ARienDeffonction2>
  </AFoncDeffonction2>
 </AProgramme>
</Start>
