<Start>
 <AProgramme>
  <AVarDecvar2>
   <ADecvar>
    <AEntierVarsimple>
     <AVarent>
     </AVarent>
    </AEntierVarsimple>
    <AVarmultiple>
     <ATabVarsimple>
      <AVartab>
      </AVartab>
     </ATabVarsimple>
     <ARienVarmultiple>
     </ARienVarmultiple>
    </AVarmultiple>
   </ADecvar>
  </AVarDecvar2>
  <AFoncDeffonction2>
   <AArgsDeffonction>
    <AMultipleFctdecvar>
     <AEntierVarsimple>
      <AVarent>
      </AVarent>
     </AEntierVarsimple>
     <ARienVarmultiple>
     </ARienVarmultiple>
    </AMultipleFctdecvar>
    <ARienDecvar2>
    </ARienDecvar2>
    <ABloc>
     <AListListinstr>
      <AAffectationInstr>
       <AAffect>
        <ASimpleVariable>
        </ASimpleVariable>
        <AExpr2Expr>
         <AExpr3Expr2>
          <AExpr4Expr3>
           <APlusExpr4>
            <AExpr5Expr4>
             <AExpr6Expr5>
              <APart7Expr6>
               <AVarExpr7>
                <ASimpleVariable>
                </ASimpleVariable>
               </AVarExpr7>
              </APart7Expr6>
             </AExpr6Expr5>
            </AExpr5Expr4>
            <AExpr6Expr5>
             <APart7Expr6>
              <ANombreExpr7>
              </ANombreExpr7>
             </APart7Expr6>
            </AExpr6Expr5>
           </APlusExpr4>
          </AExpr4Expr3>
         </AExpr3Expr2>
        </AExpr2Expr>
       </AAffect>
      </AAffectationInstr>
      <ARienListinstr>
      </ARienListinstr>
     </AListListinstr>
    </ABloc>
   </AArgsDeffonction>
   <ARienDeffonction2>
   </ARienDeffonction2>
  </AFoncDeffonction2>
 </AProgramme>
</Start>
